public class expectation2 {

    public static void main(String[] args) {
    
    try {
    
    int[] myNumbers = {1, 2, 3};
    
    System.out.println(myNumbers[8]);
    
    } catch (Exception e) {
    
    System.out.println("Something went wrong.");
    
    } finally {
    
    System.out.println("The exception handling process is completed successfully.");
    
    }
    
    }
    
    }